#lang racket

(require "Diagram-Drawing.rkt")
(require "Table-Deconstruction.rkt")
(require "Table-Construction.rkt")
(require "Table-Editing.rkt")

(provide data-structure-core)
(define (data-structure-core data-structure)
  (define master-ds null)
  (define master-table null)
  (define master-target null)
  (define master-dc null)
  (define editing-ds null)
  (define editing-table null)
  (define editing-target null)
  (define editing-dc null)
  
  (define (load-data-structure)
    (set! master-table (build-table master-ds))
    (set! master-target (make-target master-table))
    (set! master-dc (make-dc master-target))
    (set! editing-ds (copy-struct master-ds))
    (set! editing-table (copy-struct master-table))
    (set! editing-target (make-target editing-table))
    (set! editing-dc (make-dc editing-target))
    (draw-table master-table master-dc))  
  
  (define (draw-data-structure)
    (set! master-target (make-target master-table))
    (set! master-dc (make-dc master-target))
    (draw-table master-table master-dc))
  
  (define (draw-enclosed-data-structure)
    (set! master-target (make-target master-table))
    (set! master-dc (make-dc master-target))
    (draw-enclosed-table master-table master-dc))
  
  (define (replace-data-data-structure value entry)
    (set! editing-table (replace-data-entry editing-table value entry))
    (set! editing-target (make-target editing-table))
    (set! editing-dc (make-dc editing-target))
    (draw-enclosed-table editing-table editing-dc)
    editing-target)
  
    (define (replace-node-data-structure value entry)
      (set! editing-table (replace-node-entry editing-table value entry))
      (set! editing-ds (build-list editing-table))
      (set! editing-table (build-table editing-ds))
      (set! editing-target (make-target editing-table))
      (set! editing-dc (make-dc editing-target))
      (draw-enclosed-table editing-table editing-dc)
    editing-target)
  
  (define (supply-dc dc)
    (set! master-dc dc))
  
  (define (save-data-structure)
    (set! master-ds (build-list editing-table))
    (load-data-structure))
  
  (define (display-help)
    (begin
      (write "Supported Commands:")
      (newline)
      (write "draw - Draws the data structure")
      (newline)
      (write "draw-enclosed - Draws the data structure with gridlines")
      (newline)
      (write "help - Print this help menu")
      (newline)
      (write "save - Saves the data structure and returns it")
      (newline)))
  
  (define (dispatch m [replace-with null] [replace-entry null])
    (cond ((eq? m 'draw) (begin (draw-data-structure) master-target))
          ((eq? m 'draw-enclosed) (begin (draw-enclosed-data-structure) master-target))
          ((eq? m 'help) (display-help))
          ((eq? m 'load) (load-data-structure))
          ((eq? m 'peek-table) master-table)
          ((eq? m 'peek-target) master-target)
          ((eq? m 'peek-ds) master-ds)
          ((eq? m 'replace-data) (replace-data-data-structure replace-with replace-entry)) 
          ((eq? m 'save) (save-data-structure))
          (else (error "Unknown request: "
                       m))))
  
  (set! master-ds data-structure)
  (load-data-structure)
  dispatch)
    
    (define (copy-struct table)
      (if (null? table)
          null
          (cons (car table)
                (copy-struct (cdr table)))))
