#lang racket

(require racket/draw)
(require racket/gui)
(require "Diagram-Components.rkt")
(require "Diagram-Drawing.rkt")
(require "Table-Utils.rkt")

(define (paint-dc dc path target)
  (send dc draw-path path)
  (make-object image-snip% target))

(define (paint-dc-enclosed dc path target)
  (send dc draw-path enclosure)
  (send dc draw-path path)
  (make-object image-snip% target))

(define test-enclosed-target (make-bitmap 220 120))
(define test-enclosed-dc (new bitmap-dc% [bitmap test-enclosed-target]))
(define old-pen-enclosed (send test-enclosed-dc get-pen))
(define (paint-test-enclosed)
  ;Row 1
  (draw-node test-enclosed-dc enclosure 0 0)
  (draw-node test-enclosed-dc spaced-node 0 0)
  (draw-node test-enclosed-dc enclosure 0 1)
  (draw-node test-enclosed-dc spacer 0 1)
  (draw-node test-enclosed-dc enclosure 0 2)
  (draw-node test-enclosed-dc node 0 2)
  (draw-node test-enclosed-dc enclosure 0 3)
  (draw-node test-enclosed-dc terminal-node 0 3)
  ;Row 2
  (draw-node test-enclosed-dc enclosure 1 0)
  (draw-node test-enclosed-dc node 1 0)
  (draw-node test-enclosed-dc enclosure 1 1)
  (draw-node test-enclosed-dc terminal-node 1 1)
  (draw-node test-enclosed-dc enclosure 1 2)
  (draw-data test-enclosed-dc "LONNG" 1 2)
  (draw-node test-enclosed-dc enclosure 1 3)
  (draw-node test-enclosed-dc null-node 1 3)
  ;Row 3
  (draw-node test-enclosed-dc enclosure 2 0)
  (draw-data test-enclosed-dc "test" 2 0)
  (draw-node test-enclosed-dc enclosure 2 1)
  (draw-data test-enclosed-dc "data" 2 1)
  (draw-node test-enclosed-dc enclosure 2 2)
  (draw-node test-enclosed-dc enclosure 2 3)
  (make-object image-snip% test-enclosed-target))

(define test-target (make-bitmap 220 120))
(define test-dc (new bitmap-dc% [bitmap test-target]))
(define old-pen (send test-dc get-pen))
(define (paint-test)
  ;Row 1
  (draw-node test-dc spaced-node 0 0)
  (draw-node test-dc spacer 0 1)
  (draw-node test-dc node 0 2)
  (draw-node test-dc terminal-node 0 3)
  ;Row 2
  (draw-node test-dc node 1 0)
  (draw-node test-dc terminal-node 1 1)
  (draw-data test-dc "LONNG" 1 2)
  (draw-node test-dc null-node 1 3)
  ;Row 3
  (draw-data test-dc "test" 2 0)
  (draw-data test-dc "data" 2 1)
  (make-object image-snip% test-target))